<a href="https://colab.research.google.com/github/Sidhtang/machine-learining-with-CN/blob/main/general_idea_of_neural_network_without_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
Y = np.array([[0,0,0,1]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [ ]:
def sig(z):
    return 1/(1 + np.exp(-z))


In [ ]:
def derivativeSig(z):
  return sig(z)*(1-sig(z))

In [ ]:
#no hidden layer weights
weights=2*np.random.random((2,1)) -1
bias=2*np.random.random(1)-1
lr = 0.1
weights,bias

(array([[0.48388623],
        [0.34492992]]),
 array([0.88886469]))

In [ ]:
for iter in range(10000):
    output0 = X
    output = sig(np.dot(output0, weights) + bias)

    first_term = output - Y
    input_for_last_layer = np.dot(output0, weights) + bias
    second_term = derivativeSig(input_for_last_layer)
    first_two = first_term * second_term
    # Compute changes for weights and bias
    changes = np.dot(output0.T, first_two)
    bias_change = np.sum(first_two)

    # Update weights and bias
    weights = weights - lr * changes
    bias = bias - lr * bias_change

# Compute final output after training
output = sig(np.dot(X, weights) + bias)
weights, bias, output

(array([[5.47509046],
        [5.47509046]]),
 array([-8.30534709]),
 array([[2.47130443e-04],
        [5.57108958e-02],
        [5.57108959e-02],
        [9.33691862e-01]]))

In [ ]:
#general neural netwrok


